### ISSUE TITLE
Is this project WIP?

### ISSUE THREAD

**Issue by lzjluzijie** [namecoin/electrum-nmc#1]
Maybe namecoin team has already abandoned this project...

**Comment by JeremyRand** [comment]
> Is this project WIP?

Our Electrum-NMC porting work was being done by @ahmedbodi, in the repo https://github.com/Multicoin-co/electrum-nmc .  The intent was to move his work into https://github.com/namecoin/electrum-nmc/ once it had been reviewed by other Namecoin developers.  Unfortunately, last I heard Ahmed got unexpectedly busy with other things, and as a result no one has been working on Electrum-NMC recently (and we never got to the point of moving the work into this repo).

We would certainly welcome any developer who's interested in picking up where Ahmed left off.  (If no one steps up to do so, it's likely that I'll end up doing that work, but I won't have time anytime soon because I'm busy with TLS-related Namecoin dev.)  @lzjluzijie Are you, or anyone you know, by any chance interested in working on this?

**Comment by lzjluzijie** [comment]
I really love the namecoin project and I want to do something for namecoin. But my ability is not enough and I don’t know what I can do.

**Comment by JeremyRand** [comment]
> Sorry I am just a high school student and I can only write some go code.

@lzjluzijie  Lots of our existing code is in Go and would definitely benefit from another developer.  Would that be of interest?

Also, as you might have noticed, I've pushed some code to this repo today.  It seems to work fine for me (except for AuxPoW, which isn't yet implemented).  Feel free to try it out if you like, I'd love to hear test reports.

**Comment by lzjluzijie** [comment]
I'm very happy to see this. I tried to run electrum-nmc but failed. I only have a windows development platform and it seems having some problems with "iron_rc"

```bash
$ py electrum-nmc
cannot import name 'icons_rc'
Error: Could not find icons file.
Please run 'pyrcc5 icons.qrc -o gui/qt/icons_rc.py', and reinstall Electrum
```

I tried to run `pyrcc5 icons.qrc -o gui/qt/icons_rc.py` but it output nothing and the error still exist.

Can you tell me what should I do or send me a complied windows version? Thanks.

By the way, can I contact you in another way like email or telegram?

**Comment by JeremyRand** [comment]
> I'm very happy to see this. I tried to run electrum-nmc but failed. I only have a windows development platform and it seems having some problems with "iron_rc"

@lzjluzijie Does upstream Electrum work when run from source?  This sounds unrelated to any of the changes @ahmedbodi and I made.  For reference, here's what I'm running on Fedora:

~~~
pyrcc5 icons.qrc -o gui/qt/icons_rc.py
protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto
pip3 install --user .[full]
electrum-nmc
~~~

I haven't yet tried to run it on Windows, nor have I yet tried to build binaries... those are on the to-do list.

> By the way, can I contact you in another way like email or telegram?

Do you happen to have [Ricochet](https://ricochet.im/)?  That's generally my preferred messaging medium these days.

**Comment by ahmedbodi** [comment]
It sounds like your maybe trying to use iron python?
